domain: electrictx.com
header_title: 
header_image: https://firebasestorage.googleapis.com/v0/b/gigday-sites.appspot.com/o/dev-images%2Fwide-logo-1000px.png?alt=media&token=701ce4af-bf7b-467f-9244-b1e818595243
header_image_alt: Electrical Solutions of Texas

meta_description: Electrical Solutions of Texas is your professional neighborhood Texas electrican. With knowledge and experience, we can take care of all your Electial needs.

fab_icon: icon-phone
fab_label: Contact Us

google_analytics_id: 